import { createRouter, createWebHistory, RouteRecordRaw } from 'vue-router'

const routes: Array<RouteRecordRaw> = [
  { path: '/login', component: () => import('../views/login/index.vue')},
  { path: '/open', component: () => import('../views/login/open.vue')},
  { path: '/site', component: () => import('../views/login/site.vue')},
  { path: '/b/:id', component: () => import('../views/login/ban.vue')},
  { path: '/test', component: () => import('../views/layout/test.vue')},
  { path: '/ceshi', component: () => import('../views/layout/ceshi.vue')},
  {
    path: '/',
    name: 'home',
    component: () => import('../views/layout/index.vue'),
    children: [
      { path: '/home/', component: () => import('../views/index/HomeView.vue')},
      { path: '/u/:id', component: () => import('../views/index/HomeView.vue')},
      { path: '/u/:id/talk/', component: () => import('../views/talk/index.vue')},
      { path: '/talk', component: () => import('../views/index/HomeView.vue')},
      { path: '/search', component: () => import('../views/search/index.vue')},
      { path: '/u/:id/appstore/', component: () => import('../views/appstore/index.vue')},
      { path: '/u/:id/manage/', component: () => import('../views/manage/index.vue')},
      { path: '/u/:id/content/', component: () => import('../views/content/index.vue')},
      { path: '/u/:id/home/', component: () => import('../views/home/index.vue')},
      { path: '/u/:id/letter/', component: () => import('../views/letter/index.vue')},
      { path: '/u/:id/about/', component: () => import('../views/home/about.vue')},
      { path: '/u/:id/:id/', component: () => import('../views/channel/index.vue')},
      // { path: '/channel/', component: () => import('../views/channel/index.vue')},
      // { path: '/channel/action', component: () => import('../views/channel/article_action.vue')},
      // { path: '/articleList/', component: () => import('../views/channel/articleList2.vue')},
      // { path: '/articleList/action', component: () => import('../views/channel/articleAction2.vue')},
      { path: '/u/:id/info/', component: () => import('../views/basicInfo/index.vue')},
      { path: '/service/', component: () => import('../views/service/index.vue')},
      { path: '/contact/', component: () => import('../views/service/contact.vue')},
      { path: '/about/', component: () => import('../views/service/about.vue')},
      { path: '/message_board/', component: () => import('../views/service/message_board.vue')},
      { path: '/announcement/', component: () => import('../views/service/announcement.vue')},
      { path: '/u/:id/setting/', component: () => import('../views/setting/index.vue')},
      { path: '/u/:id/application/', component: () => import('../views/application/message_board/index.vue')},
      { path: '/u/:id/journal/', component: () => import('../views/application/journal/index.vue')},
      { path: '/u/:id/bookmark/', component: () => import('../views/application/bookmark/index.vue')},
      { path: '/u/:id/schedule/', component: () => import('../views/application/schedule/index.vue')},
      { path: '/activity/', component: () => import('../views/activity/index.vue')},
      // { path: '/sound/', component: () => import('../views/activity/test.vue')},
      { path: '/vote/', component: () => import('../views/vote/index.vue')},
      { path: '/u/:id/concern/', component: () => import('../views/concern/index.vue')},
      { path: '/u/:id/album/', component: () => import('../views/index/album/index.vue')},
      { path: '/u/:id/my_video/', component: () => import('../views/index/video/index.vue')},
      { path: '/u/:id/my_music/', component: () => import('../views/index/music/index.vue')},
      { path: '/u/:id/information/', component: () => import('../views/information/index.vue')},
      { path: '/u/:id/solar_terms/', component: () => import('../views/system/jieqi.vue')},
      { path: '/u/:id/constellation/', component: () => import('../views/system/constellation.vue')},
      { path: '/verified', component: () => import('../views/verified/index.vue')},
      { path: '/hao', component: () => import('../views/haosite/index.vue')},
      { path: '/question', component: () => import('../views/questions/index.vue')},
      { path: '/upload/', component: () => import('../views/upload/index.vue')},
      { path: '/learning/', component: () => import('../views/learningCenter/index.vue')},
      { path: '/sound/', component: () => import('../views/sound/index.vue')},
      { path: '/source/', component: () => import('../views/sound/source.vue')},
      { path: '/tool/', component: () => import('../views/tool/index.vue')},
      { path: '/ranking', component: () => import('../views/ranking/index.vue')},
      { path: '/surrogate', component: () => import('../views/index/page/surrogate.vue')},
      { path: '/complaint', component: () => import('../views/index/page/complaint.vue')},
      { path: '/recommend', component: () => import('../views/recommend/index.vue')},
      { path: '/camera', component: () => import('../views/recommend/index.vue')},
      { path: '/vlog', component: () => import('../views/recommend/index.vue')},
      { path: '/:id/:id/', component: () => import('../views/index/page/talkDetail.vue')},
      
    ]
  }
]

export default routes
