const getters = {
  commentStatus: (state: any) => state.commentStatus,  
  barrageSetting: (state: any) => state.barrageSetting || {}, 
  barrageStatus: (state: any) => state.barrageStatus,  
  talkList: (state: any) => state.talkList || [],  
  comprehensiveList: (state: any) => state.comprehensiveList || [],
  archive: (state: any) => state.archive || [],
  talkCollect: (state: any) => state.talkCollect || [],   
  talkComment: (state: any) => state.talkComment || [],   
  talkPraise: (state: any) => state.talkPraise || [], 
  talkForwarding: (state: any) => state.talkForwarding || [], 
  downloadList: (state: any) => state.downloadList || [],
  sourceList: (state: any) => state.sourceList || [], 
  pictureList: (state: any) => state.pictureList || [], 
  funnyList: (state: any) => state.funnyList || [], 
  techList: (state: any) => state.techList || [], 
  notesList: (state: any) => state.notesList || [], 
  websiteList: (state: any) => state.websiteList || [], 
  blogList: (state: any) => state.blogList || [], 
  wordsList: (state: any) => state.wordsList || [], 
  questionCate: (state: any) => state.questionCate || [], 
  questionsList: (state: any) => state.questionsList || [], 
  channel: (state: any) => state.channel || {}, 
  search: (state: any) => state.search || {}, 
}

export default getters;